xsd2php:
  namespaces:
    'http://signering.posten.no/schema/v1': 'Digipost\Signature\API\XML'
    'http://www.w3.org/2000/09/xmldsig#': 'Digipost\Signature\API\XML\Thirdparty\XMLdSig'
    'http://uri.etsi.org/2918/v1.2.1#': 'Digipost\Signature\API\XML\Thirdparty\ASiCe'
    'http://uri.etsi.org/01903/v1.3.2#': 'Digipost\Signature\API\XML\Thirdparty\XAdES'
  destinations_php:
    'Digipost\Signature\API\XML\Thirdparty\XMLdSig': '%digipost_signature.serializer_php_dir%/Thirdparty/XMLdSig'
    'Digipost\Signature\API\XML\Thirdparty\ASiCe': '%digipost_signature.serializer_php_dir%/Thirdparty/ASiCe'
    'Digipost\Signature\API\XML\Thirdparty\XAdES': '%digipost_signature.serializer_php_dir%/Thirdparty/XAdES'
    'Digipost\Signature\API\XML': '%digipost_signature.serializer_php_dir%'
  destinations_jms:
    'Digipost\Signature\API\XML\Thirdparty\XMLdSig': '%digipost_signature.serializer_config_dir%/XMLdSig'
    'Digipost\Signature\API\XML\Thirdparty\ASiCe': '%digipost_signature.serializer_config_dir%/ASiCe'
    'Digipost\Signature\API\XML\Thirdparty\XAdES': '%digipost_signature.serializer_config_dir%/XAdES'
    'Digipost\Signature\API\XML': '%digipost_signature.serializer_config_dir%'
  aliases:
    'http://signering.posten.no/schema/v1':
      'authentication-level': 'Digipost\Signature\API\XML\XMLAuthenticationLevel'
      'availability': 'Digipost\Signature\API\XML\XMLAvailability'
      'direct-document': 'Digipost\Signature\API\XML\XMLDirectDocument'
      'direct-signature-job-manifest': 'Digipost\Signature\API\XML\DirectSignatureJobManifest'
      'direct-signature-job-request': 'Digipost\Signature\API\XML\DirectSignatureJobRequest'
      'direct-signature-job-response': 'Digipost\Signature\API\XML\DirectSignatureJobResponse'
      'direct-signature-job-status': 'Digipost\Signature\API\XML\DirectSignatureJobStatus'
      'direct-signature-job-status-response': 'Digipost\Signature\API\XML\DirectSignatureJobStatusResponse'
      'direct-signer': 'Digipost\Signature\API\XML\XMLDirectSigner'
      'email': 'Digipost\Signature\API\XML\XMLEmail'
      'enabled': 'Digipost\Signature\API\XML\XMLEnabled'
      'error': 'Digipost\Signature\API\XML\XMLError'
      'exit-urls': 'Digipost\Signature\API\XML\XMLExitUrls'
      'identifier-in-signed-documents': 'Digipost\Signature\API\XML\XMLIdentifierInSignedDocuments'
      'notifications': 'Digipost\Signature\API\XML\XMLNotifications'
      'notifications-using-lookup': 'Digipost\Signature\API\XML\XMLNotificationsUsingLookup'
      'portal-document': 'Digipost\Signature\API\XML\XMLPortalDocument'
      'portal-signature-job-manifest': 'Digipost\Signature\API\XML\PortalSignatureJobManifest'
      'portal-signature-job-request': 'Digipost\Signature\API\XML\PortalSignatureJobRequest'
      'portal-signature-job-response': 'Digipost\Signature\API\XML\PortalSignatureJobResponse'
      'portal-signature-job-status': 'Digipost\Signature\API\XML\PortalSignatureJobStatus'
      'portal-signature-job-status-response': 'Digipost\Signature\API\XML\PortalSignatureJobStatusResponse'
      'portal-signer': 'Digipost\Signature\API\XML\XMLPortalSigner'
      'sender': 'Digipost\Signature\API\XML\XMLSender'
      'signature': 'Digipost\Signature\API\XML\XMLSignature'
      'signatures': 'Digipost\Signature\API\XML\XMLSignatures'
      'signature-status': 'Digipost\Signature\API\XML\XMLSignatureStatus'
      'signature-type': 'Digipost\Signature\API\XML\XMLSignatureType'
      'signer-specific-url': 'Digipost\Signature\API\XML\XMLSignerSpecificUrl'
      'signer-status': 'Digipost\Signature\API\XML\XMLSignerStatus'
      'signing-on-behalf-of': 'Digipost\Signature\API\XML\XMLSigningOnBehalfOf'
      'sms': 'Digipost\Signature\API\XML\XMLSms'
      'status-retrieval-method': 'Digipost\Signature\API\XML\XMLStatusRetrievalMethod'
#    'http://www.w3.org/2000/09/xmldsig#':
#      DigestValue: 'Digipost\Signature\API\XML\CustomBase64BinaryType'
    'http://www.w3.org/2001/XMLSchema':
      anyType: 'Digipost\Signature\API\XML\AnyType'
      anySimpleType: 'Digipost\Signature\API\XML\AnySimpleType'
      base64Binary: 'Digipost\Signature\API\XML\CustomBase64BinaryType'
#    'http://uri.etsi.org/01903/v1.3.2#':
#      AnyType: 'Digipost\Signature\JMS\Handler\CustomAnyTypeHandler'
#    'http://uri.etsi.org/2918/v1.2.1#':
#      AnyType: 'Digipost\Signature\JMS\Handler\CustomAnyTypeHandler'
    '##any':
      'any': 'Digipost\Signature\API\XML\AnyAnyType'
  naming_strategy: short
