<?php
/**
 * Created by PhpStorm.
 * User: bendik
 * Date: 25.07.18
 * Time: 05:41
 */

namespace Tests\DigipostSignatureBundle\Client;

//use Digipost\Signature\Client\ClientConfiguration;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ClientConfigurationTest extends KernelTestCase {

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    static::$kernel = static::createKernel();
    static::$kernel->boot();
  }

  public function testGetGlobalSender() {

    $container = static::$kernel->getContainer();
    //$clientConfig = new ClientConfiguration();
    //$clientConfig = $container->get('digipost_signature.client_config');
    /** @var \Digipost\Signature\Client\ClientConfigurationBuilder $clientConfigBuilder */
    $clientConfig = $container->get(
      'Digipost\Signature\Client\ClientConfiguration'
    );
    //    $configBuilder = $container->get('Digipost\Signature\Client\ClientConfigurationBuilder');
    //    $configBuilder->globalSender(new Sender('997123456'));
    //    $clientConfig = $configBuilder->build();
    //$clientConfig = $clientConfigBuilder->build();
    //$this->assertInstanceOf(KernelInterface::class, $container);
    print $clientConfig->getServiceRoot();
    //$clientConfig = $clientConfigBuilder->build();
  }

  public function testGetServiceRoot() {

  }

  public function testGetCertificatePaths() {

  }

  public function testGetKeyStoreConfig() {

  }

  public function testGetGuzzleConfiguration() {

  }
}
